services:
  api:
    ports: !override
      - "8001:8000"
    volumes: !override
      - ./storage:/app/storage
      - paddle_models:/root/.paddlex
      - hf_models:/root/.cache/huggingface

  worker:
    volumes: !override
      - ./storage:/app/storage
      - paddle_models:/root/.paddlex
      - hf_models:/root/.cache/huggingface

  postgres:
    ports: !override
      - "5433:5432"

  redis:
    ports: !override
      - "6380:6379"
